log:
  dir: ./
  filePrefix: log
  level: INFO
  maxKeepDays: 7
  maxFileNum: 7
  maxFileSizeInMB: 100
  isCompress: true

apiServer:
  host: 0.0.0.0
  port: 8083
  printVersionAndExit: false
  tokenExpirationHour: -1

fs:
  defaultPVPath: "./config/fs/default_pv.yaml"
  defaultPVCPath: "./config/fs/default_pvc.yaml"
  k8sServiceName: "paddleflow-server"
  K8sServicePort: 8083

namespaceList:
  - "default"

job:
  reclaim:
    isCleanJob: true
    isSkipCleanFailedJob: false
    jobTTLSeconds: 600
  schedulerName: volcano
  clusterSyncPeriod: 30
  queueSyncPeriod: 30
  jobLoopPeriod: 5
  scalarResourceArray:
    - "nvidia.com/gpu"
  defaultJobYamlDir: "./config/server/default/job"

pipeline: pipeline

imageRepository:
  server: ""
  namespace: ""
  username: ""
  password: ""
  concurrency: 10
  removeLocalImage: true

flavour:
  - name: flavour1
    cpu: 1
    mem: 1Gi
  - name: flavour2
    cpu: 1
    mem: 1Gi
    scalarResources:
      "nvidia.com/gpu": "1"
